let x = 23.2;

try {
	x += 2;
} catch {
	print("failed");
}
